apiVersion: v1
kind: Pod
metadata:
  name: flask-server-pod
spec:
  containers:
  - name: my_flask
    image: ghcr.io/rockyraccooner/devops_cicd/my_flask:latest
  imagePullSecrets:
  - name: regcred

